apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deploy
  labels:
    app: healthcare-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: healthare-container
        image: srivamsi6/healthcare-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-np-service
  labels:
    app: healthcare-app
spec:
  selector:
    app: healthcare-app

  type: NodePort
  ports:
  - nodePort: 31032    
    port: 8082
    targetPort: 8082
